# template for a general MicroSite built with mkdocs and the material theme
site_name: Mkdocs Template Site
site_description: 'Description of microsite'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/mkdocs-template/'
repo_url: 'https://github.com/dmccreary/mkdocs-template'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - Checklist: checklist.md
  - Code Highlight Test: code-highlight-test.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Feedback: feedback.md
  - License: license.md
  - Contact: contact.md
 
# Dan's Microsite Standards from here down

theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
markdown_extensions:
  # Order is important!
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
extra_javascript:
   - js/extra.js
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX